apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: wil42-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/jreverdy/iot-jereverd.git
    targetRevision: HEAD
    path: .
  destination:
    server: https://kubernetes.default.svc
    namespace: dev
  syncPolicy:
    automated:
      selfHeal: true
      prune: true